### ISSUE TITLE
Improve error logging on incoming Astarte triggers

### ISSUE THREAD

**Issue by Pavinati** [edgehog-device-manager/edgehog#219] opened 2022-09-29 10:14 UTC
When incoming events generate errors, the logs only report a generic `{:error, :cannot_process_device_event}`.
We should provide additional information to make it easier to debug what's failing and possibly why

**Comment by rbino** [comment] 2023-03-09 14:43
Closing as duplicate of #207

**Closed by rbino** 2023-03-09 14:43 UTC
